### ISSUE TITLE
Training Hardware Requirements

### ISSUE THREAD

**Issue by mayura1996** [ponimatkin/focalpose#11]
I would like to inquire about the possibility of retraining the Focalpose using a single GeForce RTX 3090 GPU with a memory capacity of 24GB. The reason for my curiosity stems from the indication in the paper that training was conducted employing a total of 40 NVIDIA A100 GPUs. Therefore, I kindly request clarification on this matter.

**Comment by ponimatkin** [comment]
Hi, we trained on 40 NVIDIA A100 since it allowed us to get results in the few hours. With respect to single RTX 3090 GPU, this should be doable memory-wise, but it might take a few days to train the model. 

Please let me know if you need any more clarification!

**Comment by mayura1996** [comment]
Thank you for the clarification
