### ISSUE TITLE
Download_data.sh Problem

### ISSUE THREAD

**Issue by LSK0821** [ponimatkin/focalpose#12]
Hello Author! Some of the data links in this file are not working, can you update them again?
![image](https://github.com/ponimatkin/focalpose/assets/69196380/fb53559a-76c6-46b9-9265-e1fd9909c968)
![image](https://github.com/ponimatkin/focalpose/assets/69196380/7cfdd9e3-dbb4-4fce-b611-fcb4cd58dcd1)

**Comment by ponimatkin** [comment]
Hi, it seems that authors have removed their official dataset from Stanford pages. I'm not sure where to get this dataset officially now. If I find some official links, I'll update them in the codebase.
