### ISSUE TITLE
TWO TCO TWC Clarification

### ISSUE THREAD

**Issue by mayura1996** [ponimatkin/focalpose#13]
obj = random.sample(objects_visible, k=1)[0]
        TWO = torch.as_tensor(obj['TWO'])
        TWC = torch.as_tensor(state['camera']['TWC'])
        TCO = invert_T(TWC) @ TWO
        
        P = K @ TCO[:, :3]

       Hi, could you please further explain these codelines in pose_dataset.py anmd camera_geometry.py
       Why you use two different cordinate systems as world and object? Cant we use the same?
       And why TCO is predicted?
       Whats the notation of TCO?
       
       Kind of unclear about the notation used in the perspective projections

**Comment by ponimatkin** [comment]
Hi,

T's are 4x4 matrices [[R t], [0 1]] (look-up SE(3) group). The rendering happens in the world coordinate system for objects and cameras are set with respect to the world coordinate system as well.

However, the algorithm needs to work in TCO (camera-object) coordinate system so we convert TWC (pose of camera in world coordinate system) and TWO (pose of object in world coordinate system) into TCO (object pose in camera coordinate system).

**Comment by mayura1996** [comment]
Thank you for the clarification
