### ISSUE TITLE
Multiple GPUs

### ISSUE THREAD

**Issue by mayura1996** [ponimatkin/focalpose#15]
Hi, Im planning to use multiple GPUs instead of 1 GPU. Could you please kindly let me know the code level changes or configs I have to done? Or is it done already in the repository?

**Comment by mayura1996** [comment]
Also my plan is to use 2 GPUs in 1 PC

**Comment by ponimatkin** [comment]
Hi, you might need to change this line: https://github.com/ponimatkin/focalpose/blob/53c59f10e9be8b91af968d520efac90a23cf7b20/focalpose/scripts/run_pose_training.py#L323

And then run the training using DDPM (i.e. initializing the job on each separate GPU) and waiting for them to sync. Please let me know if you will have any more questions regarding that.

**Comment by mayura1996** [comment]
Hi, Thank you for the clarification. I didnt quiet understand on DDPM. Do I have to make code changes or implement any script on that? Could you please clarify or provide any sources available on that. Thank you

**Comment by mayura1996** [comment]
Hi, any update on this @ponimatkin

**Comment by ponimatkin** [comment]
Hi, sorry I missed your issue!

So I'm not sure how to do it without SLURM properly (as `srun` command takes care of it automatically), but you should run identical copies of script on each separate GPU, sth like `CUDA_VISIBLE_DEVICES=0 python -m focalpose.scripts.run_pose_training` in one tmux window and then `CUDA_VISIBLE_DEVICES=1 python -m focalpose.scripts.run_pose_training` in second one. I believe there's no need to change anything in the code as `srun` should +/- do the same. You can fine more about it here: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html.
