### ISSUE TITLE
Gui-less friendly visualisation of the results?

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [ponimatkin/focalpose#2]
Hi Georgy!

Thanks for the swift and great code release. I am running it on a remote server without the option to do "ssh -X". would it be possible to have a GUI-less friendly way to look at the results? Like save a rendering of the oriented retrieved object overlayed on the image?
Would be great!

Thanks,
Thibault

Some random feedback:
-- I had to `pip install` a lot of packages, not sure the `conda install requirements` worked, or if there are packages missing.
-- Had to `apt-get install xvfb` 
-- the shebang `#!/usr/bash` caused some problems in `preprocess_data.sh` because I use zsh. Hence bash does not know conda etc...
-- It's a bit silly, but the script should explicitly tell where it stores the results, (in ./local_data/) I had to parse the code to find them.

**Comment by ponimatkin** [comment]
Hi Thibault,

- So `xvfb` is used in conjunction with MeshLabServer to patch `uv` maps and create empty textures if some are missing for Pix3D dataset. 
- Thanks for the feedback! I will modify the data preprocessing scripts in the next commit. 

Best,
Georgy

**Comment by ponimatkin** [comment]
I've addressed the issues in c6e0d8187f07f43a73a3ff48bb43c109a080c5a9, hopefully it makes sense now. 

Ad MeshLab, I will try to see if we can put the patched meshes online (I'm concerned with copyright) and if we can, then this requirement can be removed.
