### ISSUE TITLE
Segment error (core dumped)

### ISSUE THREAD

**Issue by GFENGG** [ponimatkin/focalpose#4]
Hi, when i run "  python -m focalpose.scripts.run_single_image_inference --img imgs/frame0.png --cls 'stanfordcars' --niter 15 --niter 15 ", and there exists a fault "Segment error (core dumped)"

This error appears when the code is in focalpose.scripts.run_single_image_inference.py line100:
mesh_db = MeshDataBase.from_urdf_ds(urdf_ds).batched().cuda().float()

How can i fix it?

Thank you

**Comment by ponimatkin** [comment]
Hi @GFENGG, thanks for being interested in our project!

Can I ask you for the following information:
- Could you please provide me with some information about your environment?
- Did you run all the scripts in preparation as shown in the repo?
- Could you please post the full log that you get when running the model?

Thanks!
