### ISSUE TITLE
Detecting novel class poses in test images?? Pose evaluation: error: argument --cls: invalid choice: 'my_class' (choose from 'chair', 'sofa', 'table', 'bed', 'compcars', 'stanfordcars')

### ISSUE THREAD

**Issue by monajalal** [ponimatkin/focalpose#9]
So, I am noticing that I can't get inference on novel classes? I was under the assumption that I can get inference on any new class as long as I provide its mesh.

Am I wrong? 

It seems the test image should have one of the "chair", "table", "bed", "compcars", and "stanfordcards" as its class. What if I am interested in a new class?

```
(focalpose) mona@ard-gpu-01:~/focalpose$ python -m focalpose.scripts.run_single_image_inference --img my_image.jpg --cls my_class   --niter 15 --topk 15 
Setting OMP and MKL num threads to 1.
pybullet build time: May 20 2022 19:43:01
usage: Pose evaluation [-h] [--img IMG]
                       [--cls {chair,sofa,table,bed,compcars,stanfordcars}]
                       [--niter NITER] [--topk TOPK]
Pose evaluation: error: argument --cls: invalid choice: 'my_class' (choose from 'chair', 'sofa', 'table', 'bed', 'compcars', 'stanfordcars')
```

**Comment by ponimatkin** [comment]
Unfortunately, each class needs a separate model for inference. If you are looking for model that can estimate 6DoF pose for novel objects, you can take a look at https://github.com/megapose6d/megapose6d, but that one needs camera calibrations for the training data.
